---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - watchdog.bizaikube.io
  resources:
  - policyprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watchdog.bizaikube.io
  resources:
  - policyprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - watchdog.bizaikube.io
  resources:
  - policyprofiles/status
  verbs:
  - get
  - patch
  - update
